name: Publish Common NuGet Packages

on:
  push:
    branches:
      - master
    paths:
      - "HealthCare.Common/**"
  pull_request:
    branches:
      - master
    paths:
      - "HealthCare.Common/**"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      # 1. Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      # 3. Download NuGet.exe
      - name: Install NuGet CLI
        run: |
          curl -L https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -o nuget.exe

      # 4. Find all csproj inside HealthCare.Common
      - name: Find csproj files
        id: find_projects
        shell: pwsh
        run: |
          $projects = Get-ChildItem HealthCare.Common -Recurse -Filter *.csproj | ForEach-Object { $_.FullName }
          $projectsString = $projects -join ';'
          echo "projects=$projectsString" >> $env:GITHUB_OUTPUT

      # 5. Set version = 1.0.<run_number>
      - name: Set version from run number
        id: version
        shell: pwsh
        run: |
          $newVersion = "1.0.${{ github.run_number }}"
          echo "Using version $newVersion"
          echo "version=$newVersion" >> $env:GITHUB_OUTPUT

      # 6. Restore & Build
      - name: Restore
        run: dotnet restore HealthCare.Common/HealthCare.Common.sln

      - name: Build
        run: dotnet build HealthCare.Common/HealthCare.Common.sln -c Release --no-restore

      # 7. Pack projects
      - name: Pack projects
        shell: pwsh
        run: |
          mkdir ./nupkgs
          $projects = "${{ steps.find_projects.outputs.projects }}".Split(';')
          foreach ($proj in $projects) {
            Write-Output "Packing $proj"
            dotnet pack "$proj" -c Release -o ./nupkgs /p:PackageVersion=${{ steps.version.outputs.version }} --no-build
          }

      # 8. Configure Azure Artifacts feed
      - name: Add Azure Artifacts source
        run: |
          ./nuget.exe sources Remove -Name "HealthCareFeed" || true
          ./nuget.exe sources Add -Name "HealthCareFeed" `
            -Source "https://pkgs.dev.azure.com/${{ secrets.AZURE_ORG }}/5fb94cd8-cf1a-449b-aba3-c0c4ad8b1114/_packaging/${{ secrets.AZURE_FEED_NAME }}/nuget/v3/index.json" `
            -Username "healthcarefeed" `
            -Password "${{ secrets.AZURE_FEED_PAT }}" `
            -StorePasswordInClearText

      # 9. Push packages
      - name: Push packages
        run: ./nuget.exe push "nupkgs\*.nupkg" -Source "HealthCareFeed" -ApiKey az -SkipDuplicate
        shell: pwsh
